# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        name: Check YAML (unsafe)
        args: [--unsafe]
        files: mkdocs.yml
      - id: check-yaml
        exclude: mkdocs.yml
      - id: check-added-large-files
        args: ["--maxkb", "5000"]
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--skip", "__init__.py", "--filter-files"]
      - id: isort
        name: isort (cython)
        types: [cython]
        args: ["--profile", "black"]
      - id: isort
        name: isort (pyi)
        types: [pyi]
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
  # - repo: https://github.com/asottile/blacken-docs
  #   rev: v1.10.0
  #   hooks:
  #     - id: blacken-docs
  #       exclude: notebooks/
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.19.2
    hooks:
      - id: check-github-workflows
