site_name: eds-scikit

repo_url: https://github.com/aphp/eds-scikit
repo_name: eds-scikit

theme:
  name: material
  custom_dir: mkdocs_theme
  palette:
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

  logo: _static/scikit_logo.svg
  favicon: _static/scikit_logo.svg
  features:
    - header.autohide
    - navigation.tracking
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - content.code.annotate
    # - announce.dismiss

nav:
  - index.md
  - Understanding eds-scikit:
    - project_description.md
    - A gentle demo: functionalities/generic/introduction.ipynb
  - Functionalities:
    - Connectors: functionalities/generic/io.ipynb
    - Phenotyping:
      - The `Phenotype` class: functionalities/phenotyping/base.md
      - Available phenotypes:
        - functionalities/phenotyping/phenotypes/cancer.md
        - functionalities/phenotyping/phenotypes/diabetes.md
        - functionalities/phenotyping/phenotypes/suicide_attempt.md
        - functionalities/phenotyping/phenotypes/psychiatric_disorder.md
    - Patient's Course:
      - ICU: functionalities/patients-course/is_icu.md
      - Emergency Units: functionalities/patients-course/is_emergency.md
      - Visit merging: functionalities/patients-course/visit_merging.md
      - Consultation dates: functionalities/patients-course/consultation_dates.md
    - Biology:
      - functionalities/biology/index.md
      - functionalities/biology/tutorial.ipynb
      - functionalities/biology/about_measurement.md
      - functionalities/biology/prepare_measurement.md
      - functionalities/biology/visualization.md
      - functionalities/biology/concepts_sets.md
    - Plotting:
      - Event sequence: functionalities/plotting/event_sequences.md
      - Generating inclusion/exclusion flowchart: functionalities/plotting/flowchart.ipynb
      - Age pyramid: functionalities/plotting/age_pyramid.md
  - Recipes:
    - Saving small cohorts locally: recipes/small-cohorts.ipynb
    # - Cross-tagging concepts between two DataFrames: recipes/diabetes.ipynb
  - Resources:
    - A note on private resources: datasets/private-resources.md
    - Biology:
      - Concept sets: datasets/concepts-sets.md
    - Care sites:
      - Hierarchy: datasets/care-site-hierarchy.md
      - Emergency: datasets/care-site-emergency.md
    - Synthetic data: datasets/synthetic-data.md
  - Code Reference: reference/
  - contributing.md
  - changelog.md

extra:
  version:
    provider: mike
    default: latest

extra_css:
  - _static/extra.css
  - _static/termynal/termynal.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6
  - _static/extra.js
  - _static/termynal/termynal.js

plugins:
  - search
  - markdown-filter
  - macros:
      module_name: docs/macros
  - bibtex:
      #bib_file: "docs/references.bib"
      bib_dir: "./eds_scikit"
  - gen-files:
      scripts:
        - docs/generate_reference.py
        - docs/generate_development.py
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            show_signature_annotations: true
            heading_level: 3
            members_order: source
            show_root_toc_entry: false
            separate_signature: true
            merge_init_into_class: true
  - mknotebooks
  - literate-nav:
      nav_file: SUMMARY.md
  - mike
  - autorefs
  - glightbox:
      max_preview_lines: 10
      skip_classes:
        - doc


markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ['docs/', '.']
      check_paths: true
  - pymdownx.tabbed:
      alternate_style: true
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.details
  - codehilite
