name: Testing

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"

jobs:
  check_skip:
    name: Check CI Skip
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.result_step.outputs.ci-skip }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - id: result_step
        uses: mstachniuk/ci-skip@master
        with:
          commit-filter: '[skip ci];[ci skip];[skip github]'
          commit-filter-separator: ';'

  Linting:
    name: Running pre-commit
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Set PY variable
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install pre-commit
        run: |
          pip install pre-commit
          pre-commit install
      - name: Run pre-commit
        run: SKIP=no-commit-to-branch pre-commit run --all-files

  Testing:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
    runs-on: "ubuntu-latest"
    name: 'Testing on ubuntu'
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install eds-scikit
        shell: bash {0}
        run: ./build_tools/github/install.sh
      - name: Run tests
        shell: bash {0}
        run: ./build_tools/github/test.sh
      - name: Upload coverage data
        uses: actions/upload-artifact@v4
        with:
          name: coverage-data-${{ matrix.python-version }}
          path: .coverage.*
          if-no-files-found: ignore
        if: success()
      - name: Check dependencies licenses
        run: |
          liccheck
  Coverage:
    needs: Testing
    uses: aphp/foldedtensor/.github/workflows/coverage.yml@main
    with:
      base-branch: main
      coverage-data-pattern: coverage-data-*
      coverage-report: coverage.txt
      coverage-badge: coverage.svg
      coverage-branch: coverage

  Documentation:
    needs: check_skip
    if: ${{ needs.check_skip.outputs.skip == 'false' }}
    name: Building documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.7"
    - name: Cap pip version
      run: pip install -U "pip<23"
    - name: Install dependencies
      run: pip install .[doc]
    - name: Build documentation
      run: |
        mkdocs build --clean
